esphome:
  name: scale
  friendly_name: Scale

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "=" # Update with your own key

ota:
  - platform: esphome
    password: "4" # Update with your own password

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

time:
  - platform: sntp
    id: homeassistant_time
    timezone: Europe/London
    servers:
      - pool.ntp.org
    update_interval: 30s

# I2C Bus for OLED
i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 400kHz

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    rotation: 180° # Rotate display if needed
    pages:
      - id: main_page
        lambda: |-
          // Time
          ESPTime current_time = id(homeassistant_time).now();
          if (current_time.is_valid()) {
            it.strftime(0, 0, id(my_font_12), "%H:%M:%S", current_time);
            it.strftime(0, 12, id(my_font_12), "%Y-%m-%d", current_time);
          }
          // Weight
          it.printf(0, 22, id(my_font_16), "Weight: %.1f %s", id(hx711_sensor).state, "kg");
          // it.printf(0, 35, id(my_font), "WiFi: %.0f dB", id(wifi_signal_sensor).state);
          
    update_interval: 1s

# Fonts
font:
  - file: "fonts/arial.ttf"
    id: my_font
    size: 9
    glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°µ³²"
  - file: "fonts/arial.ttf"
    id: my_font_12
    size: 12
    glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°µ³²"
  - file: "fonts/arial.ttf"
    id: my_font_16
    size: 16
    glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°µ³²"


sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 30s

  - platform: hx711
    name: "Weight Sensor"
    id: hx711_sensor
    dout_pin: GPIO18
    clk_pin: GPIO19
    gain: 128
    unit_of_measurement: "kg" # Or "kg", "lb", etc.
    update_interval: 5s # Changed from 60s to 5s
    # You will need to calibrate this value
    # 1. Place a known weight on the scale and note the raw value.
    # 2. Divide the known weight by the raw value to get a rough factor.
    # 3. Fine-tune this factor until the readings are accurate.
    filters:
      - calibrate_linear:
          - -321265 -> 0 # Zero point (no weight)
          - -332489 -> 0.406 # Example: if 100000 raw value corresponds to 1000g or 1.0kg - This is set to kg
          - -339810 -> 0.681

text_sensor:
  - platform: template
    name: "Chip Model"
    id: chip_model_text
    icon: mdi:chip
    update_interval: 600s
    lambda: |-
      esp_chip_info_t chip_info;
      esp_chip_info(&chip_info);
      if (chip_info.model == CHIP_ESP32) return {"ESP32"};
      else if (chip_info.model == CHIP_ESP32S2) return {"ESP32-S2"};
      else if (chip_info.model == CHIP_ESP32S3) return {"ESP32-S3"};
      else if (chip_info.model == CHIP_ESP32C3) return {"ESP32-C3"};
      else if (chip_info.model == CHIP_ESP32H2) return {"ESP32-H2"};
      else return {"Unknown/New Model"};

switch:
  - platform: restart
    name: "Restart device"
